# vorto.private.joaopedro.bastos.RaspberryPi3v10000 generated by Vorto Python MQTT Generator

import model.functionblock.Acceleration as acceleration
import model.functionblock.Humidity as humidity
import model.functionblock.Illuminance as illuminance
import model.functionblock.Temperature as temperature

class RaspberryPi3v10000(object):
    def __init__(self):
        self.acceleration = acceleration.Acceleration()
        self.humidity = humidity.Humidity()
        self.illuminance = illuminance.Illuminance()
        self.temperature = temperature.Temperature()
